In [1]:
import pandas as pd
df = pd.read_csv("MPI-Data-Hub_EduAttainment-Nativity & byCOB_2021.csv")
df.head(10)

,"Educational Attainment of U.S. Adults (ages 25 and over) by Nativity and Select Country of Birth, 2021",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,All Adults,Less than 9th Grade,9th-12th Grade,High School Diploma or Equivalent,Some College or Associate's Degree,Bachelor's Degree or Higher
2,U.S. Born,"188,082,000",2%,5%,27%,30%,35%
3,Immigrants,"40,208,000",16%,9%,22%,19%,34%
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Immigrants by Select Country of Birth,NaN,NaN,NaN,NaN,NaN,NaN
6,Mexico,"9,783,000",34%,17%,27%,14%,9%
7,India,"2,434,000",3%,4%,6%,7%,80%
8,China/Hong Kong,"2,073,000",13%,7%,16%,12%,52%
9,Philippines,"1,828,000",4%,3%,15%,27%,51%